<a href="https://colab.research.google.com/github/Areej973/Numpy-library-/blob/main/Numpy_library_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# The goal of the project: to measure the extent of understanding of the concepts of the numpy library

In [ ]:
import numpy as np

## Create an array of 15 floats numbers using linspace

In [ ]:
arr = np.linspace(0,2,15)
print(arr)

[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.         1.14285714 1.28571429 1.42857143 1.57142857
 1.71428571 1.85714286 2.        ]


## Create a three-dimensional (3D) matrix in the form (2, 2, 3)

In [15]:
my_3d_arr = np.array([[
    [1.1,2.1,3.1], [4.1,5.1,6.1]]
    ,[[7.1,8.1,9.1],[10.1,11.1,12.1]]])
print(my_3d_arr)
print("shape of array is: ",my_3d_arr.shape)

[[[ 1.1  2.1  3.1]
  [ 4.1  5.1  6.1]]

 [[ 7.1  8.1  9.1]
  [10.1 11.1 12.1]]]
shape of array is:  (2, 2, 3)


## Print the properties of the array

In [16]:
print("Type : ",type(my_3d_arr))
print("Data type : ",my_3d_arr.dtype)
print("Dimensions : ",my_3d_arr.ndim)
print("Shape : ",my_3d_arr.shape)
print("Size : ",my_3d_arr.size)

Type :  <class 'numpy.ndarray'>
Data type :  float64
Dimensions :  3
Shape :  (2, 2, 3)
Size :  12


## Modify the array to become 4dimensions (4D)

In [30]:
my_4d_arr = np.array(my_3d_arr,ndmin=4)
print("New array :\n",my_4d_arr)
print("New dimensions : ",my_4d_arr.ndim)
print("New shape : ",my_4d_arr.shape)

New array :
 [[[[ 1.1  2.1  3.1]
   [ 4.1  5.1  6.1]]

  [[ 7.1  8.1  9.1]
   [10.1 11.1 12.1]]]]
New dimensions :  4
New shape :  (1, 2, 2, 3)


## Change the array type to integer

In [23]:
new_arr = my_4d_arr.astype(int)
print(new_arr)
print("New data type: ",new_arr.dtype)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]
New data type:  int64


## Print all element of the array using nditer()

In [24]:
for x in np.nditer(new_arr):
  print(x , end=" ")
  print()

1 
2 
3 
4 
5 
6 
7 
8 
9 
10 
11 
12 


## Print the 8th elements in the array

In [25]:
print("8th element: ",new_arr[0,1,0,1])


8th element:  8


## Print the element number 5 and 6 in the array

In [26]:
print("5th and 6th elements: ",new_arr[0,0,1,1:])

5th and 6th elements:  [5 6]


## Search for the element number 8 using where ()

In [27]:
print(np.where(new_arr==8))

(array([0]), array([1]), array([0]), array([1]))


## Reshape the array to (2,3,2)

In [28]:
re_new_arr = new_arr.reshape(2,3,2)
print(re_new_arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## Merge the two array without specifying axis

arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

In [29]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

joined_arr = np.concatenate((arr1,arr2))
print(joined_arr)

[['A' 'B']
 ['E' 'F']
 ['C' 'D']
 ['G' 'H']]


## Merge two arrays based on rows axis = 1

In [33]:
joined_arr2 = np.concatenate((arr1,arr2),axis=1)
print(joined_arr2)

[['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']]


## Spilt the array into two arrays with axis=1

In [34]:
spilt_joined_arr2 = np.array_split(joined_arr2,2,axis=1)
print(spilt_joined_arr2)

[array([['A', 'B'],
       ['E', 'F']], dtype='<U1'), array([['C', 'D'],
       ['G', 'H']], dtype='<U1')]
